<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductsbyBrand($id)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.brand = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();

        return $query;
    }

//    public function getProductsbyCategory($id, $id2)
//    {
//        $query = $this->createQueryBuilder('p')
//            ->where('p.category = :id')
//            ->andWhere('p.secondary_category = :id2')
//            ->setParameter('id', $id)
//            ->setParameter('id2', $id2)
//            ->getQuery()
//            ->getResult();
//
//        return $query;
//    }

    public function getProductsbyCategory($id)
    {
        $query = $this->createQueryBuilder('p')
            ->andWhere('p.secondary_category = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();

        return $query;
    }
}
